# GitHub repository owner and repo name
owner: Med-ELOMARI
repo: AtlasimexStatus

sites:
  - name: Webmail Health
    url: https://webmail.atlasimex.es/api/health

  - name: Mailserver Health
    url: https://mail.atlasimex.es/healthz/ready

  - name: Office Health (Planka)
    url: https://office.atlasimex.es

status-website:
  # Base URL matches your repository name on GitHub Pages
  cname: uptime.atlasimex.es
  baseUrl: /AtlasimexStatus
  logoUrl: https://www.atlasimex.es/images/logo/logo.svg
  name: Atlasimex Status
  introTitle: "**Atlasimex** Service Status"
  introMessage: Real-time monitoring and status tracking for internal and public Atlasimex services. 
  navbar:
    - title: Status
      href: /AtlasimexStatus
    - title: GitHub
      href: https://github.com/Med-ELOMARI/AtlasimexStatus
